# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 25) do

  create_table "articles", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "synopsis",     :text
    t.column "body",         :text
    t.column "published",    :boolean,  :default => false
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "published_at", :datetime
    t.column "category_id",  :integer,  :default => 1
  end

  create_table "categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "comments", :force => true do |t|
    t.column "entry_id",    :integer
    t.column "user_id",     :integer
    t.column "guest_name",  :string
    t.column "guest_email", :string
    t.column "guest_url",   :string
    t.column "body",        :text
    t.column "created_at",  :datetime
  end

  add_index "comments", ["entry_id"], :name => "index_comments_on_entry_id"

  create_table "emails", :force => true do |t|
    t.column "from",              :string
    t.column "to",                :string
    t.column "last_send_attempt", :integer, :default => 0
    t.column "mail",              :text
  end

  create_table "entries", :force => true do |t|
    t.column "user_id",        :integer
    t.column "title",          :string
    t.column "body",           :text
    t.column "comments_count", :integer,  :default => 0, :null => false
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
  end

  add_index "entries", ["user_id"], :name => "index_entries_on_user_id"

  create_table "forums", :force => true do |t|
    t.column "name",         :string
    t.column "description",  :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "topics_count", :integer,  :default => 0, :null => false
  end

  create_table "friendships", :force => true do |t|
    t.column "user_id",          :integer,                    :null => false
    t.column "friend_id",        :integer,                    :null => false
    t.column "xfn_friend",       :boolean, :default => false, :null => false
    t.column "xfn_acquaintance", :boolean, :default => false, :null => false
    t.column "xfn_contact",      :boolean, :default => false, :null => false
    t.column "xfn_met",          :boolean, :default => false, :null => false
    t.column "xfn_coworker",     :boolean, :default => false, :null => false
    t.column "xfn_colleague",    :boolean, :default => false, :null => false
    t.column "xfn_coresident",   :boolean, :default => false, :null => false
    t.column "xfn_neighbor",     :boolean, :default => false, :null => false
    t.column "xfn_child",        :boolean, :default => false, :null => false
    t.column "xfn_parent",       :boolean, :default => false, :null => false
    t.column "xfn_sibling",      :boolean, :default => false, :null => false
    t.column "xfn_spouse",       :boolean, :default => false, :null => false
    t.column "xfn_kin",          :boolean, :default => false, :null => false
    t.column "xfn_muse",         :boolean, :default => false, :null => false
    t.column "xfn_crush",        :boolean, :default => false, :null => false
    t.column "xfn_date",         :boolean, :default => false, :null => false
    t.column "xfn_sweetheart",   :boolean, :default => false, :null => false
  end

  add_index "friendships", ["user_id", "friend_id"], :name => "index_friendships_on_user_id_and_friend_id"

  create_table "newsletters", :force => true do |t|
    t.column "subject",    :string
    t.column "body",       :text
    t.column "sent",       :boolean,  :default => false, :null => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "pages", :force => true do |t|
    t.column "title",      :string
    t.column "permalink",  :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "photos", :force => true do |t|
    t.column "user_id",      :integer
    t.column "title",        :string
    t.column "body",         :text
    t.column "created_at",   :datetime
    t.column "content_type", :string,   :limit => 100
    t.column "filename",     :string
    t.column "path",         :string
    t.column "parent_id",    :integer
    t.column "thumbnail",    :string
    t.column "size",         :integer
    t.column "width",        :integer
    t.column "height",       :integer
    t.column "geo_lat",      :float
    t.column "geo_long",     :float
    t.column "show_geo",     :boolean,                 :default => true, :null => false
  end

  create_table "posts", :force => true do |t|
    t.column "topic_id",   :integer
    t.column "user_id",    :integer
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "posts", ["topic_id"], :name => "index_posts_on_topic_id"

  create_table "roles", :force => true do |t|
    t.column "name", :string
  end

  create_table "roles_users", :id => false, :force => true do |t|
    t.column "role_id", :integer, :null => false
    t.column "user_id", :integer, :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id", "taggable_id", "taggable_type"], :name => "index_taggings_on_tag_id_and_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  add_index "tags", ["name"], :name => "index_tags_on_name"

  create_table "topics", :force => true do |t|
    t.column "forum_id",    :integer
    t.column "user_id",     :integer
    t.column "name",        :string
    t.column "created_at",  :datetime
    t.column "updated_at",  :datetime
    t.column "posts_count", :integer,  :default => 0, :null => false
  end

  add_index "topics", ["forum_id"], :name => "index_topics_on_forum_id"

  create_table "users", :force => true do |t|
    t.column "username",         :string,   :limit => 64,  :default => "",   :null => false
    t.column "email",            :string,   :limit => 128, :default => "",   :null => false
    t.column "hashed_password",  :string,   :limit => 64
    t.column "enabled",          :boolean,                 :default => true, :null => false
    t.column "profile",          :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "last_login_at",    :datetime
    t.column "posts_count",      :integer,                 :default => 0,    :null => false
    t.column "entries_count",    :integer,                 :default => 0,    :null => false
    t.column "blog_title",       :string
    t.column "enable_comments",  :boolean,                 :default => true
    t.column "photos_count",     :integer
    t.column "last_activity",    :string
    t.column "last_activity_at", :datetime
    t.column "flickr_username",  :string
    t.column "flickr_id",        :string
  end

  add_index "users", ["username"], :name => "index_users_on_username"

  create_table "usertemplates", :force => true do |t|
    t.column "user_id", :integer
    t.column "name",    :string
    t.column "body",    :text
  end

  add_index "usertemplates", ["user_id", "name"], :name => "index_usertemplates_on_user_id_and_name"

end
